import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { NavBar } from '@/components/NavBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Teste Front End',
  description: 'Generated by create next app',
  icons: {
    icon: "/Logo2.png",
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br" className="w-full h-screen">
      <body 
      className={`${inter.className} bg-white w-full h-full flex flex-col`}
      >
        <NavBar/>
        <main className="flex-grow">{children}</main>
      </body>
    </html>
  )
}
